#!/bin/zsh
# Verschlüsselung mit dem Zauberwort, mit der Lieblingszahl
# beginnend und weiter mit YY=DD und Optimismus
openssl enc -d -aes-256-cbc -a \
   -in mempass-secrets.txt.enc \
   -out mempass-secrets.txt
#
# # Instructions
#
# # encrypt file.txt to file.enc using 256-bit AES in CBC mode
# openssl enc -aes-256-cbc -salt -in file.txt -out file.enc
# # the same, only the output is base64 encoded for, e.g., e-mail
# openssl enc -aes-256-cbc -a -salt -in file.txt -out file.enc
#
# # decrypt binary file.enc
# openssl enc -d -aes-256-cbc -in file.enc -out file.txt
# # decrypt base64-encoded version
# openssl enc -d -aes-256-cbc -a -in file.enc -out file.txt
